# Generated by Django 3.2.6 on 2021-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_crawl', '0002_auto_20210822_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
