# Generated by Django 3.2.6 on 2021-09-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('product_nameId', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('Product_detailsId', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('memory', models.IntegerField(default=0)),
                ('display', models.IntegerField(default=0)),
                ('camera', models.IntegerField(default=0)),
                ('battery', models.IntegerField(default=0)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mobiles.product_type')),
            ],
        ),
    ]
