# Generated by Django 3.2.6 on 2021-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
